# junior-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test
  name: junior-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "deployments"] # Eklenecek kaynakları belirtin
  verbs: ["get", "list", "create", "delete"] # İzin verilen operasyonları belirtin
---
# production-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: production
  name: senior-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "deployments"] # Eklenecek kaynakları belirtin
  verbs: ["get", "list", "create", "delete"] # İzin verilen operasyonları belirtin

